// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VTuberMusicBoxBackend.Models;

#nullable disable

namespace VTuberMusicBoxBackend.Migrations
{
    [DbContext(typeof(MainDbContext))]
    [Migration("20231201064439_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("VTuberMusicBoxBackend.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("DateAdded")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UserDiscordId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("VideoIdList")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("UserDiscordId");

                    b.ToTable("Category");
                });

            modelBuilder.Entity("VTuberMusicBoxBackend.Models.Track", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("DateAdded")
                        .HasColumnType("datetime(6)");

                    b.Property<ushort>("EndAt")
                        .HasColumnType("smallint unsigned");

                    b.Property<bool>("IsLike")
                        .HasColumnType("tinyint(1)");

                    b.Property<ushort>("StartAt")
                        .HasColumnType("smallint unsigned");

                    b.Property<string>("UserDiscordId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("VideoId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("UserDiscordId");

                    b.ToTable("Track");
                });

            modelBuilder.Entity("VTuberMusicBoxBackend.Models.User", b =>
                {
                    b.Property<string>("DiscordId")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("DateAdded")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FavoriteTrackList")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("DiscordId");

                    b.ToTable("User");
                });

            modelBuilder.Entity("VTuberMusicBoxBackend.Models.Category", b =>
                {
                    b.HasOne("VTuberMusicBoxBackend.Models.User", null)
                        .WithMany("CategorieList")
                        .HasForeignKey("UserDiscordId");
                });

            modelBuilder.Entity("VTuberMusicBoxBackend.Models.Track", b =>
                {
                    b.HasOne("VTuberMusicBoxBackend.Models.User", null)
                        .WithMany("TrackList")
                        .HasForeignKey("UserDiscordId");
                });

            modelBuilder.Entity("VTuberMusicBoxBackend.Models.User", b =>
                {
                    b.Navigation("CategorieList");

                    b.Navigation("TrackList");
                });
#pragma warning restore 612, 618
        }
    }
}
