// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VTuberMusicBoxBackend.Models.Database;

#nullable disable

namespace VTuberMusicBoxBackend.Migrations
{
    [DbContext(typeof(MainDbContext))]
    partial class MainDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("VTuberMusicBoxBackend.Models.Database.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("DateAdded")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Guid")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<ushort>("Position")
                        .HasColumnType("smallint unsigned");

                    b.Property<string>("UserDiscordId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("VideoIdList")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("UserDiscordId");

                    b.ToTable("Category");
                });

            modelBuilder.Entity("VTuberMusicBoxBackend.Models.Database.Track", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("DateAdded")
                        .HasColumnType("datetime(6)");

                    b.Property<ushort>("EndAt")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort>("StartAt")
                        .HasColumnType("smallint unsigned");

                    b.Property<string>("UserDiscordId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("VideoId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("UserDiscordId");

                    b.ToTable("Track");
                });

            modelBuilder.Entity("VTuberMusicBoxBackend.Models.Database.User", b =>
                {
                    b.Property<string>("DiscordId")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("DateAdded")
                        .HasColumnType("datetime(6)");

                    b.HasKey("DiscordId");

                    b.ToTable("User");
                });

            modelBuilder.Entity("VTuberMusicBoxBackend.Models.Database.Category", b =>
                {
                    b.HasOne("VTuberMusicBoxBackend.Models.Database.User", null)
                        .WithMany("CategoryList")
                        .HasForeignKey("UserDiscordId");
                });

            modelBuilder.Entity("VTuberMusicBoxBackend.Models.Database.Track", b =>
                {
                    b.HasOne("VTuberMusicBoxBackend.Models.Database.User", null)
                        .WithMany("TrackList")
                        .HasForeignKey("UserDiscordId");
                });

            modelBuilder.Entity("VTuberMusicBoxBackend.Models.Database.User", b =>
                {
                    b.Navigation("CategoryList");

                    b.Navigation("TrackList");
                });
#pragma warning restore 612, 618
        }
    }
}
